In [ ]:
import numpy as np

In [ ]:
a1=np.array([10,20,30,40,50])
a2=np.arange(5)
print(a1)
print(a2)

[10 20 30 40 50]
[0 1 2 3 4]


In [ ]:
aa11=np.array([10,20,30,40,50,60],dtype=complex) # converting to specific datatypes
aa11

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j, 60.+0.j])

In [ ]:
#np.max(a1)
a1.max()

50

In [ ]:
l1=[40,30,20,60] #converting from lsit to array
al=np.array(l1)
a1

array([10, 20, 30, 40, 50])

In [ ]:
a3=a1+a2 # addition of two arrays , only same number of elements
print(a3)

[10 21 32 43 54]


In [ ]:
print(np.add(a1,a2))

[10 21 32 43 54]


In [ ]:
print(np.multiply(a1,a2)) # also perform divition(divide()) and subtraction(subtract())

[  0  20  60 120 200]


In [ ]:
a11=np.array([10.1,20.2,30.3,40.4,50.5])
a21=np.arange(4) # another way of creating array using arange() method
print(a11)
print(a21)

[10.1 20.2 30.3 40.4 50.5]
[0 1 2 3]


Arange function is used to create arrays with evenly spaced sequential values in a specified interval. 
We can specify start value, stop value, and step size.

The default start value is zero and the default step size is one.



In [ ]:
n1=np.arange(3) #with only stop value
n2=np.arange(2,6) #with start and stop values
n3=np.arange(2,10,2) #with all start, stop and step values
print(n1)
print(n2)
print(n3)

[0 1 2]
[2 3 4 5]
[2 4 6 8]


In [ ]:
m1=np.array([10,20,30,40,50])
m2=np.array([2,3,4,5,6])
print(np.mod(m1,m2)) #returns the reminder of m1/m2

[0 2 2 0 2]


In [ ]:
print(np.remainder(m1,m2)) # same as mod()

[0 2 2 0 2]


In [ ]:
a33=a11+a21 # only same size of arrays can be added
print(a33)

ValueError: ignored

In [ ]:
print(a21*5) #scalar multiplication

[ 0  5 10 15]


In [ ]:
print(a21**5) #power()

[  0   1  32 243]


In [ ]:
print(np.power(a21,5)) #using power() method

[  0   1  32 243]


np.linspace(start,stop,num=50,endpoint=bool_value,retstep=bool_value)

endpoint specifies if you want the stop value to be included.
retstep tells if you would like to know the step-value.
'num' is the number of integer to be returned where 50 is default

In [ ]:
#create an array with evenly spaced elements
np.linspace(1,5,num=5,endpoint=False,retstep=True)

(array([1. , 1.8, 2.6, 3.4, 4.2]), 0.8)

In [ ]:
arr=np.random.randint(6,size=7) #generate random integers from 0 to 6. size of the array is 7
arr

array([4, 1, 1, 5, 1, 0, 3])

In [ ]:
arrf=np.random.rand(6) #generate random 6 float values . 
arrf

array([0.47678013, 0.94737686, 0.98268574, 0.2860471 , 0.98332649,
       0.05038626])

In [ ]:
x = np.random.randint(100, size=(3, 5)) #creating 2d array with random integers
print(x)

[[83 44  0 53 27]
 [24 98 35 81  6]
 [91 69 17 60 23]]


An identity matrix is a square matrix (nxn) that has ones on the diagonal and zeros on every other position. 
Np.eye or np.identity can be used to create one.



In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr1=np.random.random(8) # to return float random values
arr1

array([0.31236554, 0.29209883, 0.52571978, 0.77076578, 0.32110403,
       0.48317302, 0.29424465, 0.87015514])

In [ ]:
aa=np.random.randint(5,size=(3,4))
aa

array([[3, 1, 3, 2],
       [2, 2, 0, 4],
       [4, 3, 2, 4]])

In [ ]:
print(aa.ravel()) # returns contiguous flattened array(1D array with all the input-array elements and with the same type as it

[2 4 4 1 1 3 4 3 0 2 4 3]


By default, an array is flattened by adding row after row. It can be changed to column-wise by setting the order parameter as F (Fortran-style).

In [ ]:
print(aa.ravel(order='F'))


[2 1 0 4 3 2 4 4 4 1 3 3]


In [ ]:
print(aa.shape)

(3, 4)


In [ ]:
print(aa.size)

12


In [ ]:
print(aa.reshape(4,3)) # reshapes an array with preserving the size 

[[2 4 4]
 [2 4 2]
 [2 3 0]
 [4 1 2]]


In [ ]:
print(aa.reshape(-1,6)) # no need to specify the size in every dimension.  let NumPy to figure out a dimension by passing -1.
print(aa.reshape(6,-1)) # could specify -1 for only one dimensions, not for both

[[2 4 4 2 4 2]
 [2 3 0 4 1 2]]
[[2 4]
 [4 2]
 [4 2]
 [2 3]
 [0 4]
 [1 2]]


In [ ]:
print(aa.transpose()) #to switch rows and columns.

[[2 4 0]
 [4 2 4]
 [4 2 1]
 [2 3 2]]


In [ ]:
aa

array([[3, 1, 3, 2],
       [2, 2, 0, 4],
       [4, 3, 2, 4]])

Splits an array into multiple sub-arrays vertically.

In [ ]:
print(np.hsplit(aa,4)) #consider column
print(np.vsplit(aa,3)) #consider row

[array([[3],
       [2],
       [4]]), array([[1],
       [2],
       [3]]), array([[3],
       [0],
       [2]]), array([[2],
       [4],
       [4]])]
[array([[3, 1, 3, 2]]), array([[2, 2, 0, 4]]), array([[4, 3, 2, 4]])]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
cat=np.concatenate((a,b)) # arrays must have same shape
print(cat)

[ 1  2  3  4 10 20 30 40]


In [ ]:
cat1=np.concatenate((a.reshape(-1,2),b.reshape(-1,2)))
print(cat1)

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


In [ ]:
vs=np.vstack((a,b)) #It is used to stack arrays vertically (rows on top of each other).
print(vs)
print(np.hstack((a.reshape(-1,2),b.reshape(-1,2))))

[[ 1  2  3  4]
 [10 20 30 40]]
[[ 1  2 10 20]
 [ 3  4 30 40]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

In [ ]:
#rawdata=open("Mall_Customers.csv")
data=np.genfromtxt('/content/drive/MyDrive/ML_lab/diabetes.csv',delimiter=',',dtype=str) #else dtype=str, max_rows=1
data
#data.shape

array([['Pregnancies', 'Glucose', 'BloodPressure', ...,
        'DiabetesPedigreeFunction', 'Age', 'Outcome'],
       ['6', '148', '72', ..., '0.627', '50', '1'],
       ['1', '85', '66', ..., '0.351', '31', '0'],
       ...,
       ['5', '121', '72', ..., '0.245', '30', '0'],
       ['1', '126', '60', ..., '0.349', '47', '1'],
       ['1', '93', '70', ..., '0.315', '23', '0']], dtype='<U24')

In [ ]:
print(data.shape)

(769, 9)


In [ ]:
print(data[768:769,:]) #retreiving last row

[['1' '93' '70' '31' '0' '30.4' '0.315' '23' '0']]


In [ ]:
ar1=data[0:5,2:4] 
ar1


array([['BloodPressure', 'SkinThickness'],
       ['72', '35'],
       ['66', '29'],
       ['64', '0'],
       ['66', '23']], dtype='<U24')

In [ ]:
arr=np.array(data,ndmin=5)
print(arr)
print(arr.ndim)
print(arr[0][0])

[[[[['Pregnancies' 'Glucose' 'BloodPressure' ...
     'DiabetesPedigreeFunction' 'Age' 'Outcome']
    ['6' '148' '72' ... '0.627' '50' '1']
    ['1' '85' '66' ... '0.351' '31' '0']
    ...
    ['5' '121' '72' ... '0.245' '30' '0']
    ['1' '126' '60' ... '0.349' '47' '1']
    ['1' '93' '70' ... '0.315' '23' '0']]]]]
5
[[['Pregnancies' 'Glucose' 'BloodPressure' ...
   'DiabetesPedigreeFunction' 'Age' 'Outcome']
  ['6' '148' '72' ... '0.627' '50' '1']
  ['1' '85' '66' ... '0.351' '31' '0']
  ...
  ['5' '121' '72' ... '0.245' '30' '0']
  ['1' '126' '60' ... '0.349' '47' '1']
  ['1' '93' '70' ... '0.315' '23' '0']]]


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


 **Use a Pandas dataframe**

Have to read the dataframe and then convert it into a numpy array by using the values function from the pandas’ library.

In [ ]:
from pandas import read_csv
df = read_csv('diabetes.csv')
data = df.values #converting from dataframe into array using values
print(data)

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
